// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Comprehensive database type to handle all table structures
interface Database {
  public: {
    Tables: {
      [tableName: string]: {
        Row: Record<string, unknown>;
        Insert: Record<string, unknown>;
        Update: Record<string, unknown>;
        Relationships: Array<{
          foreignKeyName: string;
          columns: string[];
          referencedRelation: string;
          referencedColumns: string[];
        }>;
      };
    };
    Views: Record<string, Record<string, unknown>>;
    Functions: {
      begin_transaction: {
        Args: Record<PropertyKey, never>;
        Returns: undefined;
      };
      commit_transaction: {
        Args: Record<PropertyKey, never>;
        Returns: undefined;
      };
      rollback_transaction: {
        Args: Record<PropertyKey, never>;
        Returns: undefined;
      };
      [key: string]: {
        Args: Record<string, unknown>;
        Returns: unknown;
      };
    };
    Enums: Record<string, string[]>;
    CompositeTypes: Record<string, Record<string, unknown>>;
  };
}

const supabaseUrl = 'https://qfneoowktsirwpzehgxp.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmbmVvb3drdHNpcndwemVoZ3hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0ODEwODcsImV4cCI6MjA3NzA1NzA4N30.4vuTFUVA2Wl9RimYPZKBr-cQrbxmh8ae2S-QWX-OWlQ';

if (!supabaseUrl || !supabaseAnonKey) {
  console.error('Environment variables check:', {
    supabaseUrl: supabaseUrl ? 'present' : 'missing',
    supabaseAnonKey: supabaseAnonKey ? 'present' : 'missing'
  });
  throw new Error('Missing Supabase environment variables');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);